import { collection } from 'firebase/firestore';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useCollectionData } from 'react-firebase-hooks/firestore';
import { db } from '../utils/db/firebase';
import Logo from '@public/logo-medium.svg'
import Andres from '@public/images/team/andres.jpg'
import Jacky from '@public/images/team/jacky.jpg'
import Riley from '@public/images/team/riley.jpg'
import Shan from '@public/images/team/shan.jpg'
import Will from '@public/images/team/will.jpg'
import { QuoteType } from '@/utils/types/base';
import { Quote } from '@/components/Quote';

export default function Home() {

  const [values, loading, error] = useCollectionData(
    collection(db, 'quotes')
  );

  const [quotes, setQuotes] = useState<QuoteType[]>()

  useEffect(() => {
    if (values && !quotes) {
      setQuotes(values as unknown as QuoteType[])
    }
  }, [quotes, values])

  return (
    <div className='w-screen min-h-screen'>
      <Head>
        <title>Overheard Graveyard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="images/favicon.ico" />
      </Head>

      <main className={'flex flex-col items-center w-screen min-h-screen bg-stone-100 font-sans'}>
          <div className="flex flex-col items-center justify-center w-screen md:w-1/3 py-16 px-8 md:px-0">
            <span className='text-2xl font-bond'> This is the graveyard of </span>
            <div className="relative flex items-center justify-center w-80 md:w-96"> 
              <Image src={Logo} object-fit="contain" alt=''/>
            </div>
            <span className='text-center text-xs md:text-sm'> You will be dearly remembered, and </span> 
            <span className='text-center text-xs md:text-sm'><b>always honoured at 224 E 83rd St., NY</b></span>
            <span className='text-center text-xs md:text-sm'> where your plaque hangs to this day.</span>
            <div className="mt-10 w-full space-y-6 text-sm md:text-base text-justify">
              <p> Once a blooming social network with a staggering <b>39 unique users</b>, <i>Overheard.me</i> started out as an entry to a hackathon run by the team @OnDeck, on the <b>9th of July, 2021.</b> A team from the legendary <b>Edyfi Brownstone House</b> took on the project and <b>developed Overheard in just two days.</b> Needless to say this would never have been possible without the support from the ~14 other people living at the house.</p>
              <p>{"Here's"} to the amazing team that made this happen:</p>
              <div className="flex flex-wrap items-center justify-center w-full">
                <div className="flex flex-col justify-center items-center space-y-2 mx-2 pt-4">
                  <div className="relative flex items-center justify-center w-12 h-12 md:w-16 md:h-16">
                    <Image className='rounded-full' src={Andres} object-fit="cover" alt=''/>
                  </div>
                  <div className="flex flex-col text-center text-xs">
                    <span className='font-bold'> Andres Antillon </span>
                    <span> Front-End Developer</span>
                  </div>
                </div>
                <div className="flex flex-col justify-center items-center space-y-2 mx-2 pt-4">
                  <div className="relative flex items-center justify-center w-12 h-12 md:w-16 md:h-16">
                    <Image className='rounded-full' src={Jacky} object-fit="cover" alt=''/>
                  </div>
                  <div className="flex flex-col text-center text-xs">
                    <span className='font-bold'> Jacky Zhao </span>
                    <span> Back-End Developer </span>
                  </div>
                </div>
                <div className="flex flex-col justify-center items-center space-y-2 mx-2 pt-4">
                  <div className="relative flex items-center justify-center w-12 h-12 md:w-16 md:h-16">
                    <Image className='rounded-full' src={Riley} object-fit="cover" alt=''/>
                  </div>
                  <div className="flex flex-col text-center text-xs">
                    <span className='font-bold'> Riley Walz </span>
                    <span> Full Stack Developer </span>
                  </div>
                </div>
                <div className="flex flex-col justify-center items-center space-y-2 mx-2 pt-4">
                  <div className="relative flex items-center justify-center w-12 h-12 md:w-16 md:h-16">
                    <Image className='rounded-full' src={Will} object-fit="cover" alt=''/>
                  </div>
                  <div className="flex flex-col text-center text-xs">
                    <span className='font-bold'> Will Hoppin </span>
                    <span> Designer </span>
                  </div>
                </div>
                <div className="flex flex-col justify-center items-center space-y-2 mx-2 pt-4">
                  <div className="relative flex items-center justify-center w-12 h-12 md:w-16 md:h-16">
                    <Image className='rounded-full' src={Shan} object-fit="cover" alt=''/>
                  </div>
                  <div className="flex flex-col text-center text-xs">
                    <span className='font-bold'> Shan Reddy </span>
                    <span> Product Manager </span>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-10 w-full text-sm md:text-base">
              <p> If you were one of our users, we dearly hope you enjoyed your time on Overheard, and if not, we hope you continue to enjoy it here, in its afterlife. </p>
            </div>
            <div className="mt-8 flex flex-col w-full">
              <span>{"Enjoy the quotes posted during it's lifetime - "}</span>
              <div className="flex flex-col space-y-4 py-8">
                {quotes ? quotes.map((quote, index) => (
                  <Quote key={index} quote={quote}/>
                ))
                :
                  <div className="p-12 text-center text-xl font-bold">
                    <span> Loading... </span>
                  </div>
                }
              </div>
            </div>
          </div>
      </main>

      <footer className={''}>
        
      </footer>
    </div>
  )
}
